// Auth routes are now handled entirely by Better Auth.
// All /api/auth/* endpoints are mounted in index.js via toNodeHandler(auth).
//
// Available endpoints (auto-generated by Better Auth):
//   POST /api/auth/sign-up/email
//   POST /api/auth/sign-in/email
//   POST /api/auth/sign-out
//   GET  /api/auth/get-session
//   POST /api/auth/sign-in/social  (Google OAuth)
//   POST /api/auth/organization/create
//   POST /api/auth/organization/invite-member
//   ... (see Better Auth docs for the full list)
//
// This file is kept as documentation only and is no longer imported.
